name: build and deploy container

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  service:
    uses: kubernetes-mail-server/.github/.github/workflows/service.yml@main
    secrets: inherit
    with:
      name: redis
      build: false
      helm-args: >-
        --set port=$(kubectl get cm -n mail-server services-info -o=jsonpath="{.data.REDIS_PORT}")
